### ISSUE TITLE
FragGeneScan input should be in FASTA

### ISSUE THREAD

**Issue by HadrienG** [norling/metlab#4]
hmmparse error when running the 'taxonomic classifcation' step of the analysis pipeline:
    
```
Error: Sequence file frag_gene_scan.out.faa is empty or misformatted

Traceback (most recent call last):
  File "/Users/hadrien/Documents/workspace/metlab/pipeline_scripts/vFam_HmmSearch_parse.py", line 211, in <module>
    app.run()
  File "/Users/hadrien/Documents/workspace/metlab/pipeline_scripts/vFam_HmmSearch_parse.py", line 32, in run
    dic_res = self.read_tblout()
  File "/Users/hadrien/Documents/workspace/metlab/pipeline_scripts/vFam_HmmSearch_parse.py", line 40, in read_tblout
    with open(self.resfile) as f:
IOError: [Errno 2] No such file or directory: 'hmmsearch_vFamA_table.hs'
```

It is due to FraggeneScan failing silently on Kraken FASTA output. FragGeneScan expects FASTA sequences

```
/Users/hadrien/Documents/workspace/metlab/local_apps/FragGeneScan1.20/run_FragGeneScan.pl -genome=kraken_unclassified.fasta -out=frag_gene_scan.out -complete=0 -train=illumina_5
no. of seqs: 0
```

```
head -4 kraken_unclassified.fasta
@MISEQ:41:000000000-AK2L3:1:1101:11746:1186 1:N:0:NGGCTATGNCTATCCT
GGATGAGGCGGTCCATGTCGACCTGGTTGCGCTTCGCAAGTTCGATGAGGCCCATCGTGTCGCAACCCTTGACGGT
+
CCCCCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGEGGGGGGGGGG
```

When converting the kraken output to FASTA, FragGeneScan works:
```
awk '{if(NR%4==1) {printf(">%s\n",substr($0,2));} else if(NR%4==2) print;}' kraken_unclassified.fasta > kraken_real_fasta.fasta
/Users/hadrien/Documents/workspace/metlab/local_apps/FragGeneScan1.20/run_FragGeneScan.pl -genome=kraken_real_fasta.fasta -out=frag_gene_scan.out -complete=0 -train=illumina_5
no. of seqs: 510947
```

**Comment by norling** [comment]
Good point! This happens when you don't run the assembly step with spades. I'll look into a fix asap!
